# Generated by Django 4.2.6 on 2023-11-22 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="blogs_published_no",
        ),
    ]
