# Generated by Django 4.2.6 on 2023-11-24 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_remove_user_blogs_published_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
