# Generated by Django 4.2.6 on 2023-11-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_alter_blog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
